const String dadJokeForYou = "Dad Joke For You";
const String searchDadJokes = "Search dad jokes";
const String search = "Search";
const String searchResults = "Search Results";
const String dadJoke = "Dad Joke";
const String random = "Random";
const String somethingWentWrong = "Somaething Went Wrong!";
const String internetNotConnected = "Internet Not Connected!";
const String noResultsFound = "No Results Found!";
